FROM anapsix/alpine-java
COPY century21-sell-house-collector.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]


# sudo docker build  -t flybetter/century21:full .
# sudo docker run -d flybetter/century21:full